name: 'Terraform CI'

on:
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    name: 'Format and Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.9.7'  # specify your terraform version

    - name: Terraform Format
      run: terraform fmt -recursive -check

    - name: Terraform Validate
      run: terraform validate
