name: 'Terraform CI'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main  

jobs:
  terraform:
    name: 'Format and Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check Terraform Format
      id: fmt
      run: terraform fmt -recursive -check


    - name: Terraform Initialize
      run: |
        cd terraform
        terraform init -backend=false
      env:
        TF_IN_AUTOMATION: true

    - name: Change directory and Validate Terraform
      run: |
        cd terraform
        terraform validate