name: 'Terraform CI'

on:
  pull_request_target:
    branches:
      - main  
  push:
    branches:
      - A3 

jobs:
  terraform:
    name: 'Format and Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check Terraform Format
      id: fmt
      run: |
        if ! terraform fmt -recursive -check; then
          echo "Terraform format issues found."
          exit 1
        fi

    - name: Terraform Initialize
      run: terraform init -backend=false
      env:
        TF_IN_AUTOMATION: true

    - name: Terraform Validate
      run: terraform validate
      env:
        TF_IN_AUTOMATION: true
