name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform code
        run: terraform fmt -check -recursive

      - name: Validate Terraform code
        run: terraform validate
